print('Hi! I am an AI created to interact with your today, I hope I can give you a "human" interaction today! You can call me Connie!')
your_name = input('What is your name?')
print('Nice name {}! No better than mine of course haha! '.format(your_name))
are_ready = input('To get you know more I would like to ask you some questions, are you ready?')
print('{}, nice answer! '.format(are_ready))
favorite_color = input('What is your favorite color?')
print('The color {} is a great color!'.format(favorite_color))
favorite_sport = input('And what is your favorite sport?')
print('Oh yes! I love doing {}!'.format(favorite_sport))
favorite_player = input('How is your favorite player?')
print('Oh, yes? I never heard about {}, but I bet is a good player! I will check it out later!'.format(favorite_player))